export enum Types {
  GET_LIST_POPUP = 'GET_LIST_POPUP',
  LIST_ITEM_SHOW_POPUP = 'LIST_ITEM_SHOW_POPUP',
  ITEM_SLIDER_POPUP = 'ITEM_SLIDER_POPUP',
  CLEAR_ITEM_SHOW_POPUP = 'CLEAR_ITEM_SHOW_POPUP',
  LIST_ITEM_SLIDER = 'LIST_ITEM_SLIDER'
}
